Algoritmo "Urna_Eletronica"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
candidato1:caractere
candidato2:caractere
candidato3:caractere
numerocand1:inteiro
numeroCand2:inteiro
numeroCand3:inteiro
numeroCand:inteiro
votBranco:inteiro
vot1:inteiro
vot2:inteiro
vot3:inteiro
opc:caractere
opc2:caractere
cadastroCad:

Inicio

escreval("Nome do candidato1: ")
leia(candidato1)
escreval("Informe o numero do candidato: ")
leia(numeroCand1)
limpatela
escreval("Nome do candidato2: ")
leia(candidato2)
escreval("Informe o numero do candidato: ")
leia(numeroCand2)
limpatela
escreval("Nome do candidato3: ")
leia(candidato3)
escreval("Informe o numero do candidato: ")
leia(numeroCand3)



Fimalgoritmo