Algoritmo "Urna_Eletronica"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
candidato1:caractere
candidato2:caractere
candidato3:caractere
numerocand1:inteiro
numeroCand2:inteiro
numeroCand3:inteiro
numeroCand:inteiro
votBranco:inteiro
vot1:inteiro
vot2:inteiro
vot3:inteiro
opc:caractere
opc2:caractere

Inicio

escreval("Nome do candidato1: ")
leia(candidato1)
escreval("Informe o numero do candidato: ")
leia(numeroCand1)
limpatela
escreval("Nome do candidato2: ")
leia(candidato2)
escreval("Informe o numero do candidato: ")
leia(numeroCand2)
limpatela
escreval("Nome do candidato3: ")
leia(candidato3)
escreval("Informe o numero do candidato: ")
leia(numeroCand3)
limpatela
timer(500)
escreval(".")
escreval(".")
escreval(".")
escreval(".")
escreval(".")
escreval(".")
escreval(".")
escreval(".")
timer(0)
limpatela
escreval("----------------------Eleição------------------------")
escreval("Nome candidato 1: ",candidato1," Numero: ",numeroCand1)
escreval("Nome candidato 2: ",candidato2," Numero: ",numeroCand2)
escreval("Nome candidato 3: ",candidato3," Numero: ",numeroCand3)

Fimalgoritmo